package com.aap.binaryanalyzer.features;

import com.aap.binaryanalyzer.model.FeatureVector;
import com.aap.binaryanalyzer.model.FunctionFeatureProfile;
import com.aap.binaryanalyzer.model.StructuredFeatures;
import com.aap.binaryanalyzer.util.TokenVectorizer;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Reads feature exports generated by Ghidra headless scripts. The extractor expects the input
 * file to contain a JSON object with the following shape:
 * <pre>
 * {
 *   "id": "func_401000",
 *   "disassembly": "push ebp...",
 *   "pcode": "unique_1 = ...",
 *   "strings": ["hello"],
 *   "calls": ["memcpy"],
 *   "controlFlow": {"if": 2, "loop": 1}
 * }
 * </pre>
 */
public class GhidraBinaryFeatureExtractor implements FeatureExtractor {
    private final TokenVectorizer vectorizer;
    private final ObjectMapper mapper = new ObjectMapper();

    public GhidraBinaryFeatureExtractor(int vectorDimensions) {
        this.vectorizer = new TokenVectorizer(vectorDimensions);
    }

    @Override
    public FunctionFeatureProfile extract(Path filePath, String functionId) throws IOException {
        BinaryFeatureDocument document = mapper.readValue(Files.readString(filePath), BinaryFeatureDocument.class);
        String identifier = functionId != null ? functionId : document.id;
        String textual = StreamBuilder.join(document.disassembly, document.pcode);
        FeatureVector lexical = vectorizer.vectorize(textual);
        StructuredFeatures structured = buildStructured(document);
        return new FunctionFeatureProfile(identifier, lexical, structured);
    }

    private StructuredFeatures buildStructured(BinaryFeatureDocument document) {
        Map<String, Integer> control = new HashMap<>();
        if (document.controlFlow != null) {
            control.putAll(document.controlFlow);
        }
        Set<String> calls = new HashSet<>(document.calls != null ? document.calls : List.of());
        Set<String> strings = new HashSet<>(document.strings != null ? document.strings : List.of());
        return new StructuredFeatures(control, calls, strings);
    }

    private static final class StreamBuilder {
        private StreamBuilder() {
        }

        static String join(String disassembly, String pcode) {
            return List.of(disassembly, pcode)
                    .stream()
                    .filter(Objects::nonNull)
                    .map(String::trim)
                    .filter(s -> !s.isEmpty())
                    .collect(Collectors.joining(System.lineSeparator()));
        }
    }

    private static final class BinaryFeatureDocument {
        public String id;
        public String disassembly;
        public String pcode;
        public List<String> strings;
        public List<String> calls;
        public Map<String, Integer> controlFlow;
    }
}
